# BSRNN small (non-causal): 4.8 M parameters
optim: adam
init: none
unused_parameters: true
max_epoch: 100
batch_type: folded
batch_size: 4
iterator_type: chunk
chunk_length: 32000
chunk_discard_short_samples: false
num_iters_per_epoch: 8000
num_workers: 4
grad_clip: 5.0
optim_conf:
    lr: 1.0e-03
    eps: 1.0e-08
    weight_decay: 1.0e-05
patience: 30
val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 1
scheduler: steplr
scheduler_conf:
    step_size: 2
    gamma: 0.99

allow_multi_rates: true

preprocessor: enh
channel_reordering: true
force_single_channel: true
# The categories list order must be the same everywhere in this config
categories:
- 1ch_8k
- 1ch_8k_r
- 1ch_16k_r
- 1ch_48k
- 1ch_24k
- 1ch_16k
- 2ch_8k
- 2ch_8k_r
- 2ch_16k
- 2ch_16k_r
- 5ch_8k
- 5ch_16k
- 8ch_8k_r
- 8ch_16k_r
num_spk: 1

model_conf:
    normalize_variance_per_ch: true
    # The categories list order must be the same everywhere in this config
    categories:
    - 1ch_8k
    - 1ch_8k_r
    - 1ch_16k_r
    - 1ch_48k
    - 1ch_24k
    - 1ch_16k
    - 2ch_8k
    - 2ch_8k_r
    - 2ch_16k
    - 2ch_16k_r
    - 5ch_8k
    - 5ch_16k
    - 8ch_8k_r
    - 8ch_16k_r

#====================================================
# Model configuration
#====================================================
encoder: stft
encoder_conf:
    n_fft: 960
    hop_length: 480
    use_builtin_complex: true
    default_fs: 48000
decoder: stft
decoder_conf:
    n_fft: 960
    hop_length: 480
    default_fs: 48000
separator: bsrnn
separator_conf:
    num_spk: 1
    num_channels: 64  # embedding dimension of each T-F bin
    num_layers: 6     # number of time and frequency modeling layers
    target_fs: 48000  # highest sampling frequency to model
    ref_channel: 0    # used for multichannel signals
    causal: false     # non-causal

# A list for criterions
# The overlall loss in the multi-task learning will be:
# loss = weight_1 * loss_1 + ... + weight_N * loss_N
# The default `weight` for each sub-loss is 1.0
criterions: 
  # The first criterion
  - name: mr_l1_tfd 
    conf:
      window_sz: [256, 512, 768, 1024]
      hop_sz: null
      eps: 1.0e-8
      time_domain_weight: 0.5
      normalize_variance: true
    wrapper: fixed_order
    wrapper_conf:
      weight: 1.0
  # The second criterion
  - name: si_snr 
    conf:
      eps: 1.0e-7
    wrapper: fixed_order
    wrapper_conf:
      weight: 0.0
